### ISSUE TITLE
Please upgrade Xray plugin to 1.8.4

### ISSUE THREAD

**Issue by Graveyard9988** [maskedeken/plugins#6]
https://github.com/XTLS/Xray-core/releases/tag/v1.8.4

Regards

**Comment by Graveyard9988** [comment]
Please consider upgrade for plugin

**Comment by Graveyard9988** [comment]
Please respond

**Comment by maskedeken** [comment]
https://github.com/maskedeken/plugins/releases/tag/Xray-v1.8.4
